import React from 'react'

export const About = () => {
    return (
        <div>This is an about component
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus obcaecati, corporis repellendus architecto facilis, nam ab delectus ipsam soluta quia consequuntur excepturi deserunt culpa, commodi accusantium reiciendis? Dignissimos asperiores, hic, in minus corrupti illo quibusdam doloribus vel aliquam provident voluptates placeat, ut culpa quidem debitis. Fugit possimus laboriosam esse, illo voluptatibus architecto. Repellendus quos quod quas perferendis cumque suscipit enim alias maxime neque pariatur. Maiores cupiditate velit, aperiam atque impedit cumque deleniti iste veritatis voluptatem optio, exercitationem debitis a iusto illo temporibus sint dolorem, nesciunt nobis nulla. Ullam molestias voluptatibus eius repudiandae sapiente dignissimos cumque cum perferendis laudantium expedita. Ipsa impedit quidem esse? Illum adipisci quos aliquam facilis tempora quo maxime debitis perspiciatis, in, neque iste vel magni aut! Accusantium magnam dicta quos temporibus quas enim eaque aperiam ipsum perferendis nam minus architecto quisquam, hic tempore itaque dolores, alias nesciunt quia asperiores soluta aliquam, at optio. Laborum laudantium assumenda at in blanditiis earum, eius, eum distinctio veritatis voluptate reprehenderit voluptates qui neque quibusdam repudiandae nisi autem deserunt quo accusantium alias cumque velit. Vel porro officia minus a! Maiores eum natus obcaecati architecto a quasi? Nam sed amet consectetur, expedita nihil ea, voluptas ducimus temporibus quidem eum nobis iure maiores saepe eligendi molestiae dignissimos blanditiis tempora eveniet delectus perferendis reprehenderit corrupti vel. Modi sequi ipsum rem sunt tenetur saepe, suscipit culpa labore qui ut voluptate inventore. Vero doloremque non recusandae repellendus quae enim officia obcaecati, praesentium dolorem corrupti voluptatibus ea quidem laudantium aspernatur necessitatibus voluptate rerum dolores, nesciunt mollitia reiciendis. Praesentium iure aut veritatis molestias laboriosam error! Assumenda ullam illum animi dolorum cumque. Voluptate quos recusandae unde eveniet neque architecto animi, saepe repellat et commodi vero, fugit maxime aut fugiat perspiciatis itaque praesentium illum libero ipsa! Error mollitia quaerat consequatur temporibus quibusdam iste quis reiciendis unde ullam incidunt dolor, similique nihil voluptatibus enim deserunt eligendi suscipit rerum perspiciatis assumenda voluptatem sunt! Accusamus quos modi exercitationem beatae! Quaerat vel accusantium quibusdam eum vitae necessitatibus, autem natus explicabo ex distinctio consequuntur voluptatibus tempora et ullam quis?</p>
        </div>
    )
}
